################################################################################
# Define the CloudFormation Template Version and a short description.
################################################################################
AWSTemplateFormatVersion: "2010-09-09"

Description: Creating a simple CI/CD Pipeline for a Kubernetes cluster with AWS CodePipeline.

################################################################################
# Define the AWS Resources.
################################################################################
Resources:

  ECRRepository:
    Description: ECR Repository for the docker images.
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ContainerRepository

  CodeRepository:
    Description: Code repository for the pipeline.
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Ref CodeRepositoryDescription
      RepositoryName: !Ref CodeRepositoryName

  CloudWatchEventsCanInvokePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchEventsRolePolicy
      Roles:
        - !Ref CodePipelineEventsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Resource: "*"
            Effect: Allow
            Action:
              - codepipeline:*

  CodePipelineEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CloudWatchEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Role to Invoke Pipeline when CodeCommit state changes
      EventPattern:
        source:
          - "aws.codecommit"
        detail-type:
          - "CodeCommit Repository State Change"
        resources:
          - !Ref CodeRepository
        detail:
          referenceType:
            - branch
          referenceName:
            - master
      Targets:
        - Arn: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}'
          Id: Id123
          RoleArn: !GetAtt CodePipelineEventsRole.Arn

  ServiceRoleForCodeBuild:
    Description: CodeBuild would need this service role to do its job.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "codebuild.amazonaws.com"
          Action: 
            - "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - 
                Effect: "Allow"
                Resource: 
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${BuildProjectName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${BuildProjectName}:*
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents

              - 
                Effect: "Allow"
                Resource: 
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
                  
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion

              - 
                Effect: "Allow"
                Resource: 
                  - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeRepositoryName}
                  
                Action:
                - codecommit:GitPull

  CodeBuildProject:
    Description: AWS CodeBuild project to build the Source Code
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref BuildProjectName
      Description: !Ref BuildProjectDescription
      Artifacts: 
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Sub BUILD_GENERAL1_${ComputeType}
        Image: !Ref BuildEnvironmentImage
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt ServiceRoleForCodeBuild.Arn
      Source: 
        Type: CODEPIPELINE
      Tags:
      - Key: Name
        Value: !Ref BuildProjectName

  CodePipelineArtifactStore:
    Description: An S3 bucket to serve as an artifact store for the AWS CodePipeline
    Type: AWS::S3::Bucket

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt ServiceRoleForCodePipeline.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: !GetAtt CodeRepository.Name
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: CodeCommitArtifacts
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: CodeCommitArtifacts
              OutputArtifacts:
                - Name: BuildArtifacts
              RunOrder: 1

  ServiceRoleForCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "codepipeline.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource:
                  - !Sub arn:aws:s3:::${CodePipelineArtifactStore}/*
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
              - Resource: "*"
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - cloudformation:*
                  - iam:PassRole
                  - codecommit:*
              - Resource: "*"
                Effect: Allow
                Action:
                  - lambda:*

################################################################################
# Define the Input Parameters.
################################################################################
Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:

      - Label:
          default: "Code Repository"
        Parameters:
          - CodeRepositoryName
          - BranchName
          - CodeRepositoryDescription
          - ContainerRepository

      - Label:
          default: "Build Project Details"
        Parameters:
          - BuildProjectName
          - BuildProjectDescription

      - Label:
          default: "Build Environment"
        Parameters:          
          - ComputeType
          - BuildEnvironmentImage

Parameters:

  CodeRepositoryName: 
    Description: A name for the AWS CodeCommit repository
    Type: String
    Default: CodeRepositoryName
    MinLength: 3
    MaxLength: 20
    ConstraintDescription: Must be between 3 and 20 characters.

  BranchName:
    Description: Branch name
    Type: String
    Default: master
    MinLength: 3
    MaxLength: 20
    ConstraintDescription: Must be between 3 and 20 characters.

  CodeRepositoryDescription: 
    Description: A short description for the AWS CodeCommit repository
    Type: String
    Default: "A short description for the repository"
    MinLength: 3
    MaxLength: 200
    ConstraintDescription: Must be between 3 and 200 characters.    

  ContainerRepository:
    Description: A name for the ECR repository.
    Type: String
    Default: ECRRepository
    MinLength: 3
    MaxLength: 20
    ConstraintDescription: Must be between 3 and 20 characters.

  BuildProjectName:
    Description: Name of the build project
    Type: String
    Default: DemoCodeBuildProject
    MinLength: 3
    MaxLength: 40
    ConstraintDescription: Must be between 3 and 40 characters in length. 

  BuildProjectDescription:
    Description: A short description of the build project, within 200 characters.
    Type: String
    Default: "A short description for the build project"
    MaxLength: 200
    ConstraintDescription: Must be less than 200 characters in length. 

  ComputeType:
    Description: Compute environment for build
    Type: String
    Default: SMALL
    AllowedValues:
    - SMALL
    - MEDIUM
    - LARGE
    ConstraintDescription: Compute environment small, medium or large

  BuildEnvironmentImage:
    Description: Select the run-time environment for the build. Currently, only Ubuntu Linux environment available for this selection.
    Type: String
    Default: aws/codebuild/java:openjdk-8
    AllowedValues:
    - aws/codebuild/java:openjdk-8
    - aws/codebuild/java:openjdk-9
    - aws/codebuild/nodejs:10.1.0
    - aws/codebuild/nodejs:8.11.0
    - aws/codebuild/nodejs:6.3.1
    - aws/codebuild/php:5.6
    - aws/codebuild/php:7.0
    - aws/codebuild/python:3.6.5
    - aws/codebuild/python:3.5.2
    - aws/codebuild/python:3.4.5
    - aws/codebuild/python:3.3.6
    - aws/codebuild/python:2.7.12
    - aws/codebuild/ruby:2.5.1
    - aws/codebuild/ruby:2.3.1
    - aws/codebuild/ruby:2.2.5
    - aws/codebuild/golang:1.10
    - aws/codebuild/docker:17.09.0
    - aws/codebuild/android-java-8:26.1.1
    - aws/codebuild/android-java-8:24.4.1
    ConstraintDescription: Currently, only Ubuntu Linux environment available for this selection. 

################################################################################
# Define the Outputs.
################################################################################
Outputs:

  RepositoryCloneUrlHTTP:
    Description: The URL to use for cloning the repository over HTTPS
    Value: !GetAtt CodeRepository.CloneUrlHttp

  RepositoryCloneUrlSSH:
    Description: The URL to use for cloning the repository over SSH
    Value: !GetAtt CodeRepository.CloneUrlSsh

